apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
spec:
  type: NodePort
  selector:
    app: vue-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32005
