apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
  labels:
    app: vue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-app
        image: nam2904/vue-app:latest
        ports:
        - containerPort: 80
