apiVersion: v1
kind: Service
metadata:
  name: vision_service
spec:
  type: NodePort
  selector:
    app: vision
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32006
